[project]
name = 'Decentralized-Disaster-Relief-Fund-Management'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.donation-collection]
path = 'contracts/donation-collection.clar'
clarity_version = 2
epoch = 2.5

[contracts.fund-allocation]
path = 'contracts/fund-allocation.clar'
clarity_version = 2
epoch = 2.5

[contracts.impact-reporting]
path = 'contracts/impact-reporting.clar'
clarity_version = 2
epoch = 2.5

[contracts.needs-assessment]
path = 'contracts/needs-assessment.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
